# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Raja Vundela
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rajarv.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:title/
# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# site theme(skin)
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Adding the below to _config.yml will assign the single layout and enable: author profile, reading time, comments, social sharing links, and related posts, for all posts.
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true
      toc: true # table of contents

# author (basically site owner here) if there are multiple authors create _data/authors.yml file
# /_data/authors.yml
author:
  name        : "Raja Vundela"
  bio         : "Software developer."
  avatar      : "/assets/images/raja.jpg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rajavundela"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rajavundela/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/rajavundela"

# To enable site wide search
search: true

# disqus comments
comments:
  provider: "disqus"
  disqus:
    shortname: "rajarv"

# setting repository
repository: "rajavundela/rajarv-blog"

# The default is the local time zone, as set by your operating system. changing to UTC
timezone: Etc/UTC

# describes site, used to improve seo
description: "Web Development and Tech Blogs"

masthead_title: "{ Raja Vundela }"

# These are used to dipplay tags and categories
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# pagination
paginate: 5 # amount of posts to show in home page (by default /index.html)
# paginate_path: blog/page:num/ # pagination for /blog/index (other locations)

# Footer links
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:me@rajarv.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rajavundela"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rajavundela/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/rajavundela"

# Adding _pages directory
include: ["_pages"]

# custom scripts for netlify cms identity
head_scripts:
  - https://identity.netlify.com/v1/netlify-identity-widget.js
after_footer_scripts:
  - /assets/js/netlify-identity-widget-token.js
